### ISSUE TITLE
Color Manipulation Tool: cpd export sort wrong

### ISSUE THREAD

**Issue by knowles** [seadas/seadas#18]
When you export a cpd file, the sort is alphabetical and makes it hard to hand-edit the file.
For example it does:
color0=
color1=
color10=
color11=
color2=
...

But what we really want is:
color0=
color1=
color2=
...
color10=
color11=

**Comment by aynur** [comment]
Fixed.

**Comment by knowles** [comment]
This fails to reload the saved cpd file:

I think because it's format becomes:
color00=
color01=

and it expects:
color0=
color1=

**Comment by aynur** [comment]
Okay, fixed it with loading too. Please confirm.

**Comment by knowles** [comment]
Now it won't read in all the other palettes (such as the chlor_a default) where the format is still:
color0= 

We need to continue support of this format because user's may have their own palettes at this point.  Also we want to be compatible with BEAM which (at least currently) does not support the 2 digit format
color01=

Can we achieve a sorted palette by staying with the current format?  Technically a user can define a palette of 255 points, so the 2 digit format would fail on the sort.

**Comment by aynur** [comment]
Used a more generic approach to sort colors and samples before saving in a file. Please check out.

**Comment by knowles** [comment]
Verified as fixed.  Thanks.
