### ISSUE TITLE
Geometry Export Failure with our smi files

### ISSUE THREAD

**Issue by knowles** [seadas/seadas#61]
Load one of our smi files
Open a band
Draw a rectangle
Right click on "Geometry" in File Manager to export it as shapefile

Fails with this error message:
Can not export geometry
java.lang.ClassCastException: com.vividsolutions.jts.geom.Polygon cannot be cast to com.vividsolutions.jts.geom.LineString

A workaround to this.
Create a lat and a lon band
Attach geo-coding 
Save file - then reopen file (this step is a workaround to a 2nd bug, see next ticket)

Now a shapefile can be exported.

**Comment by knowles** [comment]
Note that a user has now posted regarding this bug.
http://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?pid=25667
So when repaired we should note it there on the forum.

**Comment by dshea** [comment]
Fixed. See if it works for you, Danny

**Comment by knowles** [comment]
Checks out.
