### ISSUE TITLE
Color Bar Layer cause inability to save a session

### ISSUE THREAD

**Issue by knowles** [seadas/seadas#69]
Open a L3 file
Create a color bar layer
Save session

The session does not get saved.  No warning message to user.

If you create a color bar layer, then delete the layer, the session can once again be saved.

**Comment by aynur** [comment]
Look at it before next release.

**Comment by aynur** [comment]
Fixed. 
Cause: "Session Save" serializes layers before saving them, but ColorBarLayer does not implement serialization. 
Fix: ColorBarLayer is excluded from the list of layers to be saved in a session.

**Comment by aynur** [comment]
Please confirm that issue #67 is resolved.

**Comment by knowles** [comment]
This issue is fixed.  #67 is not.
