### ISSUE TITLE
SeaDAS Window Content Draw Bug

### ISSUE THREAD

**Issue by 7yl4r** [seadas/seadas#86]
This bug may not be unique to SeaDAS, but I haven't encountered a similar problem on this system yet. I need to find a workaround because this makes SeaDAS nearly unusable.

### Description
[Video demo of problem](https://youtu.be/ICywLIknDzA). UI elements in the SeaDAS window do not draw unless they are changed somehow. Window resizing also does not trigger redraw of UI elements. Advice on what to call this might help me find solutions as well.

### To Reproduce
This is a fresh install of SeaDAS-7.3.2 on Lubuntu 16.04.2 LTS 64-bit & Intel® Ivybridge Desktop graphics driver, same behavior observed in LXDE and GNOME window managers.

**Comment by swbailey** [comment]
This is a known issue when openjdk is used.  The solution is to install the official Java jre from Oracle.
