### ISSUE TITLE
when i input the command:mvn install -DskipTests=true,the terminal shows so many errors.

### ISSUE THREAD

**Issue by VipWangQiaoqiao** [seadas/seadas#89]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]
[ERROR]   The project gov.nasa.gsfc.seadas:seadas-help:[unknown-version] (E:\SeaDAS\seadas\seadas-help\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for gov.nasa.gsfc.seadas:seadas-help:[unknown-version]: Failure to find gov.nasa.gsfc.seadas:seadas:pom:7.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 23, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project gov.nasa.gsfc.seadas:seadas-bathymetry-operator:1.0 (E:\SeaDAS\seadas\seadas-bathymetry-operator\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for gov.nasa.gsfc.seadas:seadas-bathymetry-operator:1.0: Failure to find gov.nasa.gsfc.seadas:seadas:pom:7.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project gov.nasa.gsfc.seadas:seadas:7.4.1 (E:\seadas\seadas\pom.xml) has 39 errors
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-core of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-csv-dataio of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-gpf of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-python of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-scripting of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-ui of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-visat of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-visat-rcp of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-alos-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-atsr-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-avhrr-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-binning of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-chris-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-cluster-analysis of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-collocation of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-envisat-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-envi-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-geotiff of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-getasse30-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-hdf5-writer of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-landsat-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-merisl3-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-modis-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-netcdf of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-opendap of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-pconvert of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-pixel-extraction of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-proba-v-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-rtp-codec of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-pgx-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-spot-vgt-reader of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-statistics-op of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-temporal-percentile-op of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-time-series-tool of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-unmix of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\blue-marble-worldmap of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\globcover-worldmap of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\lib-hdf of E:\seadas\seadas\pom.xml does not exist
[ERROR]     Child module E:\seadas\seadas\..\beam\beam-bigtiff of E:\seadas\seadas\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by swbailey** [comment]
There were a few inconsistent version entries in the POM files.  Should be resolved now.
